version: "3.7"
services:
  app:
    build:
      context: .
    environment:
      PORT: "80"
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/ping"]
      interval: 30s
      timeout: 3s
      retries: 3
  load_test:
    build:
      context: .
    command: ["locust", "--clients=10", "--hatch-rate=0.1", "--host=http://app:80", "--no-web"]
    depends_on:
      - app
    ports:
      - "8089"